apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "kafka-lag-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-lag-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-lag-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "kafka-lag-exporter.fullname" . }}-serviceaccount
      volumes:
        - name: cacerts
          configMap:
            name: ca-bundle
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_LAG_EXPORTER_PORT
              value: "{{ .Values.service.port }}"
            - name: KAFKA_LAG_EXPORTER_POLL_INTERVAL_SECONDS
              value: "{{ .Values.pollIntervalSeconds }} seconds"
            - name: KAFKA_LAG_EXPORTER_POLL_LOOKUP_TABLE_SIZE
              value: "{{ .Values.lookupTableSize }}"
            - name: KAFKA_LAG_EXPORTER_CLIENT_GROUP_ID
              value: "{{ .Values.clientGroupId }}"
            - name: ROOT_LOG_LEVEL
              value: "{{ .Values.rootLogLevel }}"
            - name: KAFKA_LAG_EXPORTER_LOG_LEVEL
              value: "{{ .Values.kafkaLagExporterLogLevel }}"
            - name: KAFKA_LAG_EXPORTER_KAFKA_LOG_LEVEL
              value: "{{ .Values.kafkaLogLevel }}"
            - name: KAFKA_LAG_EXPORTER_KAFKA_CLIENT_TIMEOUT_SECONDS
              value: "{{ .Values.kafkaClientTimeoutSeconds }} seconds"
            - name: KAFKA_LAG_EXPORTER_STRIMZI
              value: "{{ .Values.watchers.strimzi }}"
            {{- range $index, $cluster := .Values.clusters }}
            - name: "KAFKA_LAG_EXPORTER_CLUSTERS.{{ $index }}.name"
              value: "{{ $cluster.name }}"
            - name: "KAFKA_LAG_EXPORTER_CLUSTERS.{{ $index }}.bootstrap-brokers"
              value: "{{ $cluster.bootstrapBrokers }}"
            {{- if $cluster.securityProtocol }}
            - name: "KAFKA_LAG_EXPORTER_CLUSTERS.{{ $index }}.security-protocol"
              value: "{{ $cluster.securityProtocol }}"
            {{- end }}
            {{- if $cluster.saslMechanism }}
            - name: "KAFKA_LAG_EXPORTER_CLUSTERS.{{ $index }}.sasl-mechanism"
              value: "{{ $cluster.saslMechanism }}"
            {{- end }}
            {{- if $cluster.saslJaasConfig }}
            - name: "KAFKA_LAG_EXPORTER_CLUSTERS.{{ $index }}.sasl-jaas-config"
              value: "{{ $cluster.saslJaasConfig }}"
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: cacerts
              mountPath: /etc/pki/ca-trust/extracted/java/cacerts
              subPath: ca-bundle.jks
              readOnly: true
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
