runAsUser: 10001

## Statically define 1 or more cluster
clusters: {}
## Ex)
# clusters:
#  - name: "default"
#    bootstrapBrokers: "my-cluster-kafka-bootstrap:9092"
#    # optional values for TLS/SASL enabled clusters
#    securityProtocol: SASL_SSL
#    saslMechanism: PLAIN
#    saslJaasConfig: org.apache.kafka.common.security.plain.PlainLoginModule required username=\"foo\" password=\"bar\";

## The interval between refreshing metrics
pollIntervalSeconds: 5
## Size of the sliding window of offsets to keep in each partition's lookup table
lookupTableSize: 20
## The Consumer Group `group.id` to use when connecting to Kafka
clientGroupId: "kafkalagexporter"
## The log level of the ROOT logger
rootLogLevel: INFO
## The log level of Kafka Lag Exporter
kafkaLagExporterLogLevel: INFO
## The log level of `org.apache.kafka` logger
kafkaLogLevel: INFO
## The timeout when communicating with Kafka clusters
kafkaClientTimeoutSeconds: 10
## Watchers will automatically discover and forget Kafka clusters
watchers:
  ## The Strimzi Cluster Watcher automatically watches for `kafka.strimzi.io` group, `Kafka` kind resources and will
  ## configure the Kafka Lag Exporter appropriately.
  strimzi: false

## You probably won't need to change anything below this line.
image:
  repository: lightbend/kafka-lag-exporter
  tag: 0.4.1-SNAPSHOT
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
